<div class="container content-bg px-0 container-category">
        <h1 class="text-center mb-4">Adatvédelmi nyilatkozat</h1>
        <div class="row w-100 mx-0">
            <div class="col-12 px-0 text-center mx-auto mt-3">
                <h3>Lorem, ipsum dolor.</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, harum! Ipsum illum, quisquam inventore obcaecati, qui porro voluptate harum repellendus sequi ad cupiditate numquam eligendi eveniet? Saepe consequatur eveniet ut nulla modi placeat dicta necessitatibus voluptatem quas, qui facilis explicabo labore nobis et facere mollitia maiores, reprehenderit atque id eligendi corporis distinctio architecto. Corporis, animi voluptas. Eius, blanditiis? Natus doloremque necessitatibus pariatur dignissimos repellat blanditiis similique ex nostrum assumenda? Rerum necessitatibus earum et fugiat enim amet ipsa, beatae laborum eaque optio sit omnis quasi dicta. Quo blanditiis dolores quae sint? Accusamus iure hic ipsam voluptate veniam exercitationem, libero delectus similique, eaque autem, dolore incidunt commodi recusandae numquam ipsa est explicabo! Impedit sapiente aliquam, molestias enim eveniet possimus doloremque adipisci, consequuntur nobis esse corrupti odio eos, repellat animi magni! Rerum alias, eligendi quasi labore optio laudantium adipisci blanditiis eum numquam debitis, animi quia aut laboriosam? Doloremque dolorem ut neque fugit sint.</p>

                <h3>Lorem ipsum dolor sit.</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet ipsam accusantium tempora, id, dolor omnis laboriosam libero minima cumque animi soluta, possimus amet. Debitis, aliquid! Saepe, asperiores, totam minus eos cumque dolore consectetur consequuntur quaerat, provident quam fugiat labore optio obcaecati! Quos nam corporis dolor ut veritatis, ipsum aliquid adipisci quod? Delectus saepe temporibus voluptate repudiandae, nostrum minus. Harum delectus, porro maiores vel, nulla soluta dolores reprehenderit ut ad, obcaecati veritatis unde vitae eum ipsum. Fugit harum assumenda, tempore totam porro iste ipsa eius nemo inventore dignissimos quam consequatur. Dolor esse aspernatur quae amet ratione laborum voluptate aperiam expedita deserunt.</p>

                <h3>Lorem, ipsum.</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus aperiam quisquam ipsa fugit, animi ullam, facere laboriosam commodi reiciendis minus mollitia labore soluta excepturi debitis deserunt autem impedit, perspiciatis officia ad libero nihil a. Dolorem ratione quis porro mollitia illum. Modi provident molestiae tenetur laudantium quae itaque perferendis possimus quas beatae ex ipsum id accusantium, veritatis vitae consequuntur facilis tempora quam impedit accusamus aspernatur omnis debitis! Quidem quia facilis eum, dolores dignissimos nihil aspernatur eaque in, nemo labore provident saepe ad porro officia iusto dicta voluptatibus. Voluptate sit cumque temporibus est eius quidem eveniet? Aut veritatis at voluptatum, iusto corporis rerum facere ipsum sed saepe itaque delectus velit porro cum sunt aperiam reprehenderit ab sequi dolorum nemo. Mollitia, amet! Eligendi nemo provident impedit vero ullam animi atque magni totam assumenda saepe repellendus officia amet nesciunt itaque, eveniet sit cum nostrum ab? Commodi, voluptatibus exercitationem quibusdam et nostrum esse maiores optio consequuntur fuga? Incidunt dignissimos labore, omnis harum aliquid eligendi voluptates aut similique consectetur error, laudantium libero dolore voluptatibus adipisci molestias beatae quam commodi nesciunt expedita. Non amet repudiandae ipsum laboriosam. Ducimus ex suscipit at minima id molestiae dolores repudiandae laborum, voluptas sequi saepe sed? Nostrum tenetur pariatur odit tempore explicabo?</p>
            </div>
        </div>
</div>